Feature/update fta models
wesleymonte/fogbow-site-probe pull request #19
Opened 2019-09-12 20:43 UTC by wesleymonte

2019-09-13 00:29 UTC, joivo requested changes

2019-09-13 00:29 UTC, joivo commented on probes/src/main/java/cloud/fogbow/probes/core/probes/FogbowResourceAvailabilityProbe.java
> +        this.help = "Metric measures the level of failure to request a resource after your Order is Open.";
Replace by `Measures the level of failure to request a resource after the Order is open.`

2019-09-13 00:29 UTC, joivo commented on probes/src/main/java/cloud/fogbow/probes/core/probes/FogbowServiceLatencyProbe.java
> +        this.help = "Latency is measured by the time that elapses between the order being opened until order are available.";
Replace by `The time that elapses between the order being opened until the order is available.`

2019-09-13 00:29 UTC, joivo commented on probes/src/main/java/cloud/fogbow/probes/core/probes/FogbowServiceReachabilityProbe.java
> +        this.help = "Monitoring the availability of Fogbow services.";
Replace by `Returns 0 if the target service is not available or 1 if is.`

2019-09-13 00:29 UTC, joivo commented on probes/src/main/java/cloud/fogbow/probes/core/probes/FogbowServiceSuccessRateProbe.java
> +        this.help = "Measuring the success rate in requesting a resource.";
Remove the `measuring` word.

2019-09-13 17:10 UTC, wesleymonte commented on probes/src/main/java/cloud/fogbow/probes/core/probes/FogbowResourceAvailabilityProbe.java
> +        this.help = "Metric measures the level of failure to request a resource after your Order is Open.";
Done.

2019-09-13 17:11 UTC, wesleymonte commented on probes/src/main/java/cloud/fogbow/probes/core/probes/FogbowServiceLatencyProbe.java
> +        this.help = "Latency is measured by the time that elapses between the order being opened until order are available.";
Done.

2019-09-13 17:11 UTC, wesleymonte commented on probes/src/main/java/cloud/fogbow/probes/core/probes/FogbowServiceReachabilityProbe.java
> +        this.help = "Monitoring the availability of Fogbow services.";
Done.

2019-09-13 17:11 UTC, wesleymonte commented on probes/src/main/java/cloud/fogbow/probes/core/probes/FogbowServiceSuccessRateProbe.java
> +        this.help = "Measuring the success rate in requesting a resource.";
Done.

2019-09-14 00:26 UTC, joivo approved these changes

2019-09-14 00:27 UTC, merged